spa_backend_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: SpaBackendBundle:Default:index }

spa_backend_upload:
    pattern:  /upload
    defaults: { _controller: SpaBackendBundle:Default:index }


SpaBackendBundle_produto:
    resource: "@SpaBackendBundle/Resources/config/routing/product.yml"
    prefix:   /produto

SpaBackendBundle_video:
        resource: "@SpaBackendBundle/Resources/config/routing/video.yml"
        prefix:   /video

SpaBackendBundle_unidades:
        resource: "@SpaBackendBundle/Resources/config/routing/unit.yml"
        prefix:   /unidades

SpaBackendBundle_slider:
        resource: "@SpaBackendBundle/Resources/config/routing/slider.yml"
        prefix:   /bannerslider

SpaBackendBundle_bannersimples:
        resource: "@SpaBackendBundle/Resources/config/routing/simplebanner.yml"
        prefix:   /bannersimples

SpaBackendBundle_bannerduplo:
        resource: "@SpaBackendBundle/Resources/config/routing/doublebanner.yml"
        prefix:   /bannerduplo

SpaBackendBundle_bannerdireita:
        resource: "@SpaBackendBundle/Resources/config/routing/rightbanner.yml"
        prefix:   /bannerdireita

SpaBackendBundle_bannerunidades:
        resource: "@SpaBackendBundle/Resources/config/routing/bannerunity.yml"
        prefix:   /bannerunidades

SpaBackendBundle_noticias:
        resource: "@SpaBackendBundle/Resources/config/routing/post.yml"
        prefix:   /noticias

SpaBackendBundle_servicos:
        resource: "@SpaBackendBundle/Resources/config/routing/service.yml"
        prefix:   /servicos

SpaBackendBundle_promocao:
        resource: "@SpaBackendBundle/Resources/config/routing/promotion.yml"
        prefix:   /promocao
        