spa_backend_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: SpaBackendBundle:Default:index }

SpaBackendBundle_produto:
    resource: "@SpaBackendBundle/Resources/config/routing/product.yml"
    prefix:   /produto

SpaBackendBundle_video:
        resource: "@SpaBackendBundle/Resources/config/routing/video.yml"
        prefix:   /video

SpaBackendBundle_unidades:
        resource: "@SpaBackendBundle/Resources/config/routing/unit.yml"
        prefix:   /unidades

SpaBackendBundle_slider:
        resource: "@SpaBackendBundle/Resources/config/routing/slider.yml"
        prefix:   /slider