spa_backend_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: SpaBackendBundle:Default:index }

spa_backend_upload:
    pattern:  /upload
    defaults: { _controller: SpaBackendBundle:Default:index }

spa_backend_index:
    pattern:  /
    defaults: { _controller: SpaBackendBundle:Default:index }

login:
    pattern:   /login
    defaults:  { _controller: SpaBackendBundle:Default:login }

login_check:
    pattern:   /login_check

logout:
    path:   /logout

send_password:
    pattern:   /enviarsenha/{email}
    defaults:  { _controller: SpaBackendBundle:Default:sendPassword }

page_banners:
    pattern:   /banners/{page}
    defaults:  { _controller: SpaBackendBundle:Default:pageBanner }

add_page_banner:
    pattern:  /{banner}/addpagebanner/{page}
    defaults: { _controller: "SpaBackendBundle:Default:addPageBanner" }

SpaBackendBundle_produto:
    resource: "@SpaBackendBundle/Resources/config/routing/product.yml"
    prefix:   /produto

SpaBackendBundle_video:
        resource: "@SpaBackendBundle/Resources/config/routing/video.yml"
        prefix:   /video

SpaBackendBundle_unidades:
        resource: "@SpaBackendBundle/Resources/config/routing/unit.yml"
        prefix:   /unidades

SpaBackendBundle_slider:
        resource: "@SpaBackendBundle/Resources/config/routing/slider.yml"
        prefix:   /bannerslider

SpaBackendBundle_bannersimples:
        resource: "@SpaBackendBundle/Resources/config/routing/simplebanner.yml"
        prefix:   /destaqueprincipal

SpaBackendBundle_bannerduplo:
        resource: "@SpaBackendBundle/Resources/config/routing/doublebanner.yml"
        prefix:   /bannerduplo

SpaBackendBundle_bannerdireita:
        resource: "@SpaBackendBundle/Resources/config/routing/rightbanner.yml"
        prefix:   /bannerdireita

SpaBackendBundle_bannerunidades:
        resource: "@SpaBackendBundle/Resources/config/routing/bannerunity.yml"
        prefix:   /bannerunidades

SpaBackendBundle_noticias:
        resource: "@SpaBackendBundle/Resources/config/routing/post.yml"
        prefix:   /noticias

SpaBackendBundle_servicos:
        resource: "@SpaBackendBundle/Resources/config/routing/service.yml"
        prefix:   /servicos

SpaBackendBundle_promocao:
        resource: "@SpaBackendBundle/Resources/config/routing/promotion.yml"
        prefix:   /promocao

SpaBackendBundle_usuarios:
        resource: "@SpaBackendBundle/Resources/config/routing/user.yml"
        prefix:   /usuarios

SpaBackendBundle_admins:
        resource: "@SpaBackendBundle/Resources/config/routing/adminuser.yml"
        prefix:   /admins

SpaBackendBundle_menu:
        resource: "@SpaBackendBundle/Resources/config/routing/menu.yml"
        prefix:   /menu

SpaBackendBundle_submenu:
        resource: "@SpaBackendBundle/Resources/config/routing/submenu.yml"
        prefix:   /submenu

SpaBackendBundle_banners:
        resource: "@SpaBackendBundle/Resources/config/routing/banner.yml"
        prefix:   /banner

SpaBackendBundle_pagecontent:
        resource: "@SpaBackendBundle/Resources/config/routing/pagecontent.yml"
        prefix:   /content

