spa_backend:
    resource: "@SpaBackendBundle/Resources/config/routing.yml"
    prefix:   /admin

spa_members:
    resource: "@SpaFrontendBundle/Resources/config/members/routing.yml"
    prefix:   /franqueado

spa_frontend:
    resource: "@SpaFrontendBundle/Resources/config/routing.yml"
    prefix:   /



_imagine:
    resource: .
    type:     imagine



