spa_frontend_homepage:
    pattern:  /
    defaults: { _controller: SpaFrontendBundle:Default:index }

spa_frontend_sendmail:
    pattern:  /sendmail
    defaults: { _controller: SpaFrontendBundle:Default:sendMail }
    methods:  [POST]

spa_frontend_sendmailfaleconosco:
    pattern:  /sendmailfaleconosco
    defaults: { _controller: SpaFrontendBundle:Default:sendMailFaleConosco }
    methods:  [POST]


spa_frontend_menu:
    pattern:  /{slug}
    defaults: { _controller: SpaFrontendBundle:Default:menu }

spa_frontend_submenu:
    pattern:  /{slug}/{subslug}
    defaults: { _controller: SpaFrontendBundle:Default:subMenu }

spa_frontend_unit:
    pattern:  /unidades
    defaults: { _controller: SpaFrontendBundle:Default:unit }

spa_frontend_find_unit:
    pattern:  /buscaUnidade/{uf}/{city}
    defaults: { _controller: SpaFrontendBundle:Default:findUnit, city: '' }

spa_frontend_addunit:
    pattern:  /vai
    defaults: { _controller: SpaFrontendBundle:Default:addUnit }

spa_frontend_viewmap:
    pattern:  /mapinha
    defaults: { _controller: SpaFrontendBundle:Default:viewMap }

spa_frontend_news:
    pattern:  /noticias
    defaults: { _controller: SpaFrontendBundle:Default:news }

spa_frontend_view_post:
    pattern:  /noticia/{post}
    defaults: { _controller: SpaFrontendBundle:Default:viewPost }

spa_frontend_services:
    pattern:  /servicos
    defaults: { _controller: SpaFrontendBundle:Default:services }

spa_frontend_show_service:
    pattern:  /servicos/{slug}
    defaults: { _controller: SpaFrontendBundle:Default:viewService }

spa_frontend_promotion:
    pattern:  /promocoes
    defaults: { _controller: SpaFrontendBundle:Default:promotion }

spa_frontend_view_promotion:
    pattern:  /promocoes/{slug}
    defaults: { _controller: SpaFrontendBundle:Default:viewPromotion }

spa_frontend_product:
    pattern:  /produtos
    defaults: { _controller: SpaFrontendBundle:Default:product }

spa_frontend_view_product:
    pattern:  /produtos/{slug}
    defaults: { _controller: SpaFrontendBundle:Default:viewProduct }

spa_frontend_sejafranqueado:
    pattern:  /seja-um-franqueado
    defaults: { _controller: SpaFrontendBundle:Default:sejaFranqueado }

spa_frontend_faleconosco:
    pattern:  /faleconosco
    defaults: { _controller: SpaFrontendBundle:Default:sejaFranqueado }

spa_frontend_institucional:
    pattern:  /institucional
    defaults: { _controller: SpaFrontendBundle:Default:institucional }

spa_frontend_contact:
    pattern:  /faleconosco
    defaults: { _controller: SpaFrontendBundle:Default:contact }


