spa_frontend_homepage:
    pattern:  /
    defaults: { _controller: SpaFrontendBundle:Default:index }

spa_frontend_product:
    pattern:  /produtos
    defaults: { _controller: SpaFrontendBundle:Default:product }

spa_frontend_unit:
    pattern:  /unidades
    defaults: { _controller: SpaFrontendBundle:Default:unit }

spa_frontend_find_unit:
    pattern:  /buscaUnidade/{uf}
    defaults: { _controller: SpaFrontendBundle:Default:findUnit }