spa_frontend_homepage:
    pattern:  /
    defaults: { _controller: SpaFrontendBundle:Default:index }

spa_frontend_product:
    pattern:  /produtos
    defaults: { _controller: SpaFrontendBundle:Default:product }

spa_frontend_unit:
    pattern:  /unidades
    defaults: { _controller: SpaFrontendBundle:Default:unit }

spa_frontend_find_unit:
    pattern:  /buscaUnidade/{uf}/{city}
    defaults: { _controller: SpaFrontendBundle:Default:findUnit, city: '' }

spa_frontend_addunit:
    pattern:  /vai
    defaults: { _controller: SpaFrontendBundle:Default:addUnit }

spa_frontend_viewmap:
    pattern:  /mapinha
    defaults: { _controller: SpaFrontendBundle:Default:viewMap }

spa_frontend_news:
    pattern:  /noticias
    defaults: { _controller: SpaFrontendBundle:Default:news }

spa_frontend_view_post:
    pattern:  /noticia/{post}
    defaults: { _controller: SpaFrontendBundle:Default:viewPost }

spa_frontend_services:
    pattern:  /servicos
    defaults: { _controller: SpaFrontendBundle:Default:services }