spa_frontend_homepage:
    pattern:  /
    defaults: { _controller: SpaFrontendBundle:Default:index }

spa_frontend_product:
    pattern:  /produtos
    defaults: { _controller: SpaFrontendBundle:Default:product }
