Spa\BackendBundle\Entity\PageBanner:
    type: entity
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        page:
            type: string
            length: 255
        bannerId:
            type: integer
            column: banner_id
        hided:
            type: boolean
        position:
            type: integer
        createdAt:
            type: datetime
            column: created_at
        updatedAt:
            type: datetime
            column: updated_at
    manyToOne:
        banner:
          targetEntity: Banner
          inversedBy: banners
    lifecycleCallbacks:
        prePersist: [ updatedTimestamps ]
        preUpdate: [ updatedTimestamps ]
