Spa\BackendBundle\Entity\PageContent:
    type: entity
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        page:
            type: string
            length: 255
        content:
            type: text
        form:
            type: text
            nullable: true
        createdAt:
            type: datetime
            column: created_at
        updatedAt:
            type: datetime
            column: updated_at
    lifecycleCallbacks:
        prePersist: [ updatedTimestamps ]
        preUpdate: [ updatedTimestamps ]
