Spa\BackendBundle\Entity\Product:
    type: entity
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        name:
            type: string
            length: 255
        info:
            type: text
        path:
            type: string
            length: 255
    lifecycleCallbacks:
        prePersist: [ preUpload ]
        postPersist: [ upload ]
