Spa\BackendBundle\Entity\Product:
    type: entity
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        name:
            type: string
            length: 255
        description:
            type: text
        pic:
            type: string
            length: 255
            nullable: TRUE
        createdAt:
            type: datetime
            column: created_at
        updatedAt:
            type: datetime
            column: updated_at
        productCategoryId:
            type: integer
            column: productCategory_id
            nullable: true
        hided:
            type: boolean
            nullable: true
        position:
            type: integer
            nullable: true
        slug:
                type: string
                length: 128
                gedmo:
                    slug:
                        separator: -
                        style: camel
                        fields:
                            - name
    manyToOne:
        productCategory:
          targetEntity: ProductCategory
          inversedBy: productCategory
    indexes:
        search_idx:
            columns: slug
    lifecycleCallbacks:
        prePersist: [ preUpload, updatedTimestamps ]
        preUpdate: [ updatedTimestamps ]
        postPersist: [ upload ]

