Spa\BackendBundle\Entity\Video:
    type: entity
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        url:
            type: string
            length: 255
        type:
            type: string
            length: 255
        pic:
            type: string
            length: 255
            nullable: true
        description:
            type: text
            nullable: true
        createdAt:
            type: datetime
            column: created_at
        updatedAt:
            type: datetime
            column: updated_at
    lifecycleCallbacks:
        prePersist: [ preUpload, updatedTimestamps ]
        preUpdate: [ updatedTimestamps ]
        postPersist: [ upload ]
