<?php

namespace Spa\BackendBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DoubleBannerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DoubleBannerRepository extends EntityRepository
{
}
